application:
  subdomain: dozzle
  upstreams:
    - location: /
      backend: http://dozzle:8080/
services:
  dozzle:
    # upstream: docker.io/amir20/dozzle:v11.0.0
    image: docker.1ms.run/amir20/dozzle:v11.0.0
    environment:
      - DOZZLE_ADDR=:8080
      - DOZZLE_NO_ANALYTICS=true
    binds:
      - /lzcapp/var/data:/data
